### ISSUE TITLE
Guild unit search do not work on iPhone X

### ISSUE THREAD

**Issue by celsogbj** [jedi-gg/swgoh.gg.public#408] opened 2018-09-23 13:16 UTC
The unit search for guilds is not working on Safari / iPhone X.

**Comment by Kazanori** [comment] 2018-09-24 17:09
This is iOS wide and really needs sorting asap

**Comment by dkkd** [comment] 2018-10-11 18:52
Guild unit search don’t work on iPhone

**Comment by scobenes** [comment] 2022-01-15 01:16
duplicate of https://github.com/jedi-gg/swgoh.gg.public/issues/394

**Closed by scobenes** 2022-01-15 01:16 UTC
Labels: duplicate
