### ISSUE TITLE
Gear 13 listing wrong for Resistance Heroes

### ISSUE THREAD

**Issue by TKEMotown** [jedi-gg/swgoh.gg.public#662] opened 2020-10-28 14:05 UTC
When trying to farm gear for Resistance Hero Poe and Resistance Hero Finn what is listed is wrong.  When I promoted them to Gear 12, I should have had all the gear needed to promote them to G13, but I was missing 2 pieces for Poe and 4 for Finn.  Would be great if those could be updated so others don't run into this issue.  Thanks!

**Comment by scobenes** [comment] 2020-11-02 20:18
when you say the gear listed is wrong, could you screenshot or give me a URL of where that is.  Will help me look into what is going on. Thanks

**Comment by TKEMotown** [comment] 2020-11-02 22:55
The gear listed as needed to get RH Poe and RH Finn on the pages listed below were missing items I needed when I got to G12.

Specifically I think both needed about 100 Mk 12 Armatek Fusion Furnace Salvage each as well as other items.

https://swgoh.gg/characters/resistance-hero-finn/gear/
https://swgoh.gg/characters/resistance-hero-poe/gear/

**Comment by scobenes** [comment] 2020-11-06 03:26
I cant 100% confirm ingame since I have both of them relic'ed but, I just checked in multiple locations and it looks like the gear for g12 is correct.  Looking at their gear I def see them both need 100/150 of the Mk 12 ArmaTek Fusion Furnace salvage.

I'd have to see an ingame screenshot, but I am going to consider this as not a bug as everything looks completely correct to me.

Finn:
![image](https://user-images.githubusercontent.com/3346556/98322628-840a4180-1fad-11eb-932b-5c9acc5051db.png)

Poe:
![image](https://user-images.githubusercontent.com/3346556/98322643-8c627c80-1fad-11eb-8614-44b55f5f3064.png)

**Closed by scobenes** 2020-11-06 03:26 UTC
