### ISSUE TITLE
Filter 'Counter' searches for every word 'encounter' in descriptions, too

### ISSUE THREAD

**Issue by azgo** [jedi-gg/swgoh.gg.public#406] opened 2018-09-22 15:33 UTC
The Characters page's Filter function Ability Class\Counter selects every characters which has the word encounter in their description. 

Please fix to select only with the whole word 'Counter'.

**Comment by scobenes** [comment] 2022-01-15 01:15
duplicate of https://github.com/jedi-gg/swgoh.gg.public/issues/328

**Closed by scobenes** 2022-01-15 01:15 UTC
Labels: duplicate
