### ISSUE TITLE
Guild squad template

### ISSUE THREAD

**Issue by bfiliatreault** [jedi-gg/swgoh.gg.public#631] opened 2020-05-10 17:41 UTC
My guild's squad templates dosen't work anymore :

https://swgoh.gg/g/2520/quebec-force-sith/squad-templates/

I'm login trough swgoh.gg, and it keeps asking me to relogin.

**Comment by polaris2828** [comment] 2020-05-26 14:51
Me too

**Comment by Eksosel** [comment] 2020-05-27 19:31
I have the same issue on our guild.

**Comment by ChrisCucs** [comment] 2020-06-08 21:33
Same here, the link redirect me to the log in page

**Comment by Heroman-nebelreich** [comment] 2020-07-28 10:23
Same here, the link redirect me to the log in page
https://swgoh.gg/accounts/login/?next=/g/29948/nebelreich/squad-templates/

Will this issue be solved, when buying a patreon account?

**Comment by danpaulson** [comment] 2020-07-28 15:02
I'm going to work on a fix for this as it's been a longstanding issue. Will update when I get it deployed as I'm not able to reproduce.

**Comment by Heroman-nebelreich** [comment] 2020-07-28 17:22
Thank you for taking care of this problem. Maybe this supplement will help with troubleshooting. The problem did not occur until the eighth squad was accounted for. Seven of them were still operating without complaint.

**Comment by Heroman-nebelreich** [comment] 2020-07-28 17:25
Thank you, it works again

**Comment by Heroman-nebelreich** [comment] 2020-07-28 20:51
![image](https://user-images.githubusercontent.com/68902767/88720169-b857a180-d124-11ea-9489-251f6fda2456.png)

Now an Error 503 occurs

**Comment by scobenes** [comment] 2022-01-15 02:19
This is most likely an old bug

**Closed by scobenes** 2022-01-15 02:19 UTC
Labels: wontfix
